version: '3.3'

secrets:
  secret-counselling-gmaps:
    file:  secret-counselling-gmaps.txt
  secret-editing-recaptcha-en:
    file:  secret-editing-recaptcha-en.txt
  secret-editing-editors:
    file: secret-editing-editors.csv
  secret-soci-gmaps:
    file:  secret-soci-gmaps.txt
  secret-soci-mchimp-amici:
    file:  secret-soci-mchimp-amici.txt
  secret-soci-mchimp:
    file:  secret-soci-mchimp.txt
  secret-soci-recaptcha:
    file: secret-soci-recaptcha.txt
  secret-leaflet:
    file: secret-leaflet.txt

services:
   db:
     image: mysql:5.6.41
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: airiopenlab/wordpress:php5.6-apache
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     secrets:
        - secret-counselling-gmaps
        - secret-editing-editors
        - secret-editing-recaptcha-en
        - secret-soci-gmaps
        - secret-soci-mchimp-amici
        - secret-soci-mchimp
        - secret-soci-recaptcha
        - secret-leaflet
        
volumes:
    db_data: {}
